Algoritmo "Exercicio 6"
// Disciplina   : [Algoritimos e Lógica de Programação]
// Professor   : Carmen
// Descrição   : Conta a partir de numero menor que 6
// Autor(a)    : Ygor Gabriel
// Data atual  : 14/09/2025
Var
   // Seção de Declarações das variáveis
   num, i : inteiro

Inicio
   // Seção de Comandos, procedimento, funções, operadores, etc...
   Escreva("Digite um número menor do 6: ")
   Leia(num)

   Enquanto num > 6 faca
      Escreva("Digite um número menor do 6: ")
      Leia(num)
   Fimenquanto

   Para i de num ate 100 passo 2 faca
      Escreval(i)
   Fimpara

Fimalgoritmo