Algoritmo "Exercicio 1"
// Disciplina   : [Algoritimos e Lógica de Programação]
// Professor   : Carmen
// Descrição   : Exibe nome, idade e signo
// Autor(a)    : Ygor Gabriel
// Data atual  : 18/08/2025
Var
// Seção de Declarações das variáveis 


Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
   Escreva("Nome: Ygor - Idade: 25 anos")
   Escreval()
   Escreval()
   Escreval()
   Escreval()
   Escreval("Nome: Paloma - Signo: Aquário")
   Escreval()
   Escreval()
   Escreval("-------------------------------")
Fimalgoritmo