Algoritmo "Exercicio 2"
// Disciplina   : [Algoritimos e Lógica de Programação]
// Professor   : Carmen
// Descrição   : Recebe nome e faz uma saudação
// Autor(a)    : Ygor Gabriel
// Data atual  : 18/08/2025
Var
// Seção de Declarações das variáveis 
nome : caractere

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
   escreval("Tudo bem? Qual o seu nome? ")
   leia(nome)
   escreval("Legal " + nome + " foi bom te conhecer.")
Fimalgoritmo