Algoritmo "SomaDoisNumeros"
// Disciplina   : [Algoritimos e Lógica de Programação]
// Professor   : Carmen
// Descrição   : Soma dois numeros
// Autor(a)    : Ygor Gabriel
Var
   // Seção de Declarações das variáveis
   num1, num2, soma : inteiro

Inicio
   // Seção de Comandos, procedimento, funções, operadores, etc...
   Escreva("Digite o primeiro numero: ")
   Leia(num1)
   Escreval()
   Escreva("Digite o segundo numero: ")
   Leia(num2)
   Escreval()
   soma <- num1 + num2
   Escreva("A soma e: ", soma)
Fimalgoritmo